name: 2.4.$(Rev:r)

resources:
- repo: self

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/*

pool:
  vmImage: 'ubuntu-latest'
  
steps:
- checkout: self
  clean: true

- task: UseDotNet@2 
  displayName: "Install .NET"
  inputs:
    version: '9.0.x'
    packageType: sdk
    
- script: |
    dotnet tool install -g dotnet-setversion --ignore-failed-sources
    dotnet tool update -g dotnet-setversion --ignore-failed-sources
    cd src/Adliance.QmDoc
    setversion $(Build.BuildNumber)
  displayName: 'Set Version'

- task: UseDotNet@2
  displayName: "Install .NET"
  inputs:
    version: '10.0.x'
    packageType: sdk

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: './src/Adliance.QmDoc/Adliance.QmDoc.csproj'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: './src/Adliance.QmDoc/Adliance.QmDoc.csproj'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: pack
    packagesToPack: './src/Adliance.QmDoc/*.csproj'
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
    versioningScheme: byBuildNumber
    
- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
    PathToPublish: '$(Build.ArtifactStagingDirectory)'    
        
- task: DotNetCoreCLI@2
  displayName: Push
  inputs:
    command: 'custom'
    custom: 'nuget'
    arguments: >
      push "$(Build.ArtifactStagingDirectory)/*.nupkg"
      --source "https://api.nuget.org/v3/index.json"
      --api-key "$(NUGET_API_KEY)"

