name: 2.1.$(Rev:r)

resources:
- repo: self

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/*

pool:
  vmImage: 'windows-latest'
  
steps:
- checkout: self
  clean: true

- task: UseDotNet@2 
  displayName: "Install .NET"
  inputs:
    version: '8.0.x'
    packageType: sdk
    
- script: |
    dotnet tool install -g dotnet-setversion --ignore-failed-sources
    dotnet tool update -g dotnet-setversion --ignore-failed-sources
    cd src/Adliance.QmDoc
    setversion $(Build.BuildNumber)
  displayName: 'Set Version'

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: './src/Adliance.QmDoc/Adliance.QmDoc.csproj'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: './src/Adliance.QmDoc/Adliance.QmDoc.csproj'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: DotNet Pack
  inputs:
    command: pack
    packagesToPack: './src/Adliance.QmDoc/Adliance.QmDoc.csproj'
    versioningScheme: byBuildNumber

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'

- task: NuGetCommand@2
  displayName: NuGet Push
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'Public NuGet'


